"""The learning feedback loop: log manual overrides, feed them back as
Claude API examples, and auto-promote repeated corrections into permanent
rules.
"""
from __future__ import annotations

import csv
import re
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from src.config import MerchantRule, Settings
from src.models import Transaction

CORRECTIONS_FILENAME = "corrections.csv"
FIELDNAMES = ["corrected_at", "row_id", "description", "pattern", "category", "subcategory"]


@dataclass
class CorrectionRecord:
    corrected_at: str
    row_id: str
    description: str
    pattern: str
    category: str
    subcategory: str


def normalize_pattern(description: str) -> str:
    """Collapse a description down to a stable merchant pattern by dropping
    digits (transaction IDs, dates, store numbers) — simple string
    normalization, no fuzzy matching or ML.
    """
    text = description.upper().strip()
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def _corrections_path(settings: Settings) -> Path:
    settings.corrections_dir.mkdir(parents=True, exist_ok=True)
    return settings.corrections_dir / CORRECTIONS_FILENAME


def record_correction(settings: Settings, transaction: Transaction, category: str, subcategory: str) -> None:
    path = _corrections_path(settings)
    is_new = not path.exists()
    with open(path, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDNAMES)
        if is_new:
            writer.writeheader()
        writer.writerow({
            "corrected_at": datetime.now(timezone.utc).isoformat(),
            "row_id": transaction.row_id,
            "description": transaction.description,
            "pattern": normalize_pattern(transaction.description),
            "category": category,
            "subcategory": subcategory,
        })


def load_all_corrections(settings: Settings) -> list[CorrectionRecord]:
    path = _corrections_path(settings)
    if not path.exists():
        return []
    with open(path, "r", newline="") as f:
        reader = csv.DictReader(f)
        return [CorrectionRecord(**row) for row in reader]


def load_recent_corrections(settings: Settings, n: int | None = None) -> list[CorrectionRecord]:
    n = n or settings.max_recent_corrections
    records = load_all_corrections(settings)
    return records[-n:]


def corrections_lookup(settings: Settings) -> dict[str, CorrectionRecord]:
    """Pattern -> most recent correction for that pattern (last write wins)."""
    lookup: dict[str, CorrectionRecord] = {}
    for record in load_all_corrections(settings):
        lookup[record.pattern] = record
    return lookup


def promote_rules(settings: Settings) -> list[MerchantRule]:
    """Promote any pattern corrected >= promote_after_n_corrections times
    into config/learned_rules.yaml. Returns the newly-added rules.
    """
    records = load_all_corrections(settings)
    counts = Counter(r.pattern for r in records)
    latest_by_pattern = {r.pattern: r for r in records}

    learned_path = Path(settings.raw["paths"]["learned_rules_file"])
    if not learned_path.is_absolute():
        from src.config import ROOT
        learned_path = ROOT / learned_path

    existing = _read_learned_rules(learned_path)
    existing_keywords = {r["keyword"] for r in existing}

    newly_added = []
    for pattern, count in counts.items():
        if count < settings.promote_after_n_corrections:
            continue
        if not pattern or pattern in existing_keywords:
            continue
        record = latest_by_pattern[pattern]
        rule = {"keyword": pattern, "category": record.category, "subcategory": record.subcategory}
        existing.append(rule)
        existing_keywords.add(pattern)
        newly_added.append(MerchantRule(keyword=pattern, category=record.category, subcategory=record.subcategory, origin="learned"))

    if newly_added:
        _write_learned_rules(learned_path, existing)

    return newly_added


def _read_learned_rules(path: Path) -> list[dict]:
    if not path.exists():
        return []
    import yaml
    with open(path, "r") as f:
        data = yaml.safe_load(f) or {}
    return list(data.get("rules") or [])


def _write_learned_rules(path: Path, rules: list[dict]) -> None:
    import yaml
    header = (
        "# Auto-generated by the corrections feedback loop (src/corrections.py).\n"
        "#\n"
        "# When the same description pattern has been manually corrected at least\n"
        "# `corrections.promote_after_n_corrections` times (see settings.yaml), it is\n"
        "# promoted here as a permanent rule so you don't have to keep correcting it.\n"
        "#\n"
        "# Do not hand-edit the `rules` list structure below — the promotion logic\n"
        "# rewrites this file. Feel free to delete entries you no longer want.\n\n"
    )
    with open(path, "w") as f:
        f.write(header)
        yaml.safe_dump({"rules": rules}, f, sort_keys=False)
